[2020-12-28 09:00:03,385] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [queued]>
[2020-12-28 09:00:03,388] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [queued]>
[2020-12-28 09:00:03,388] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 09:00:03,388] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-28 09:00:03,388] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 09:00:03,397] {taskinstance.py:1038} INFO - Executing <Task(SSHOperator): t1> on 2020-12-27T01:00:00+00:00
[2020-12-28 09:00:03,399] {standard_task_runner.py:51} INFO - Started process 14235 to run task
[2020-12-28 09:00:03,405] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 't1', '2020-12-27T01:00:00+00:00', '--job-id', '55', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpeqaebs04']
[2020-12-28 09:00:03,405] {standard_task_runner.py:76} INFO - Job 55: Subtask t1
[2020-12-28 09:00:03,425] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [running]> on host dataiku
[2020-12-28 09:00:03,443] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2020-12-27T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-27T01:00:00+00:00
[2020-12-28 09:00:03,443] {ssh.py:90} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2020-12-28 09:00:03,446] {base.py:74} INFO - Using connection to: id: crawler_server. Host: 172.16.16.119, Port: 22, Schema: , Login: ub, Password: XXXXXXXX, extra: None
[2020-12-28 09:00:03,447] {ssh.py:197} WARNING - Remote Identification Change is not verified. This wont protect against Man-In-The-Middle attacks
[2020-12-28 09:00:03,448] {ssh.py:202} WARNING - No Host Key Verification. This wont protect against Man-In-The-Middle attacks
[2020-12-28 09:00:03,454] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2020-12-28 09:00:03,467] {transport.py:1819} INFO - Authentication (password) successful!
[2020-12-28 09:00:03,467] {ssh.py:109} INFO - Running command: echo "airflow"
[2020-12-28 09:00:03,741] {ssh.py:141} INFO - airflow
[2020-12-28 09:00:03,755] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=foodpanda, task_id=t1, execution_date=20201227T010000, start_date=20201228T010003, end_date=20201228T010003
[2020-12-28 09:00:03,772] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2020-12-28 09:00:03,777] {local_task_job.py:118} INFO - Task exited with return code 0
[2020-12-28 10:34:12,229] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [queued]>
[2020-12-28 10:34:12,231] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [queued]>
[2020-12-28 10:34:12,231] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 10:34:12,231] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-28 10:34:12,231] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 10:34:12,240] {taskinstance.py:1038} INFO - Executing <Task(SSHOperator): t1> on 2020-12-27T01:00:00+00:00
[2020-12-28 10:34:12,242] {standard_task_runner.py:51} INFO - Started process 22584 to run task
[2020-12-28 10:34:12,244] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 't1', '2020-12-27T01:00:00+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpw_cwrgak']
[2020-12-28 10:34:12,245] {standard_task_runner.py:76} INFO - Job 62: Subtask t1
[2020-12-28 10:34:12,261] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [running]> on host dataiku
[2020-12-28 10:34:12,277] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2020-12-27T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-27T01:00:00+00:00
[2020-12-28 10:34:12,277] {ssh.py:90} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2020-12-28 10:34:12,280] {base.py:74} INFO - Using connection to: id: crawler_server. Host: 172.16.16.119, Port: 22, Schema: , Login: ub, Password: XXXXXXXX, extra: None
[2020-12-28 10:34:12,280] {ssh.py:197} WARNING - Remote Identification Change is not verified. This wont protect against Man-In-The-Middle attacks
[2020-12-28 10:34:12,280] {ssh.py:202} WARNING - No Host Key Verification. This wont protect against Man-In-The-Middle attacks
[2020-12-28 10:34:12,284] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2020-12-28 10:34:12,293] {transport.py:1819} INFO - Authentication (password) successful!
[2020-12-28 10:34:12,294] {ssh.py:109} INFO - Running command: echo "airflow"
[2020-12-28 10:34:12,403] {ssh.py:141} INFO - airflow
[2020-12-28 10:34:12,413] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=foodpanda, task_id=t1, execution_date=20201227T010000, start_date=20201228T023412, end_date=20201228T023412
[2020-12-28 10:34:12,430] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2020-12-28 10:34:12,456] {local_task_job.py:118} INFO - Task exited with return code 0
[2020-12-28 13:36:22,864] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [queued]>
[2020-12-28 13:36:22,884] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [queued]>
[2020-12-28 13:36:22,884] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 13:36:22,884] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-28 13:36:22,884] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 13:36:22,892] {taskinstance.py:1038} INFO - Executing <Task(SSHOperator): t1> on 2020-12-27T01:00:00+00:00
[2020-12-28 13:36:22,894] {standard_task_runner.py:51} INFO - Started process 23160 to run task
[2020-12-28 13:36:22,897] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 't1', '2020-12-27T01:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpgrcrfj10']
[2020-12-28 13:36:22,897] {standard_task_runner.py:76} INFO - Job 4: Subtask t1
[2020-12-28 13:36:22,967] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.t1 2020-12-27T01:00:00+00:00 [running]> on host dataiku
[2020-12-28 13:36:23,017] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2020-12-27T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-27T01:00:00+00:00
[2020-12-28 13:36:23,017] {ssh.py:90} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2020-12-28 13:36:23,032] {taskinstance.py:1396} ERROR - SSH operator error: The conn_id `crawler_server` isn't defined
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/ssh/operators/ssh.py", line 92, in execute
    self.ssh_hook = SSHHook(ssh_conn_id=self.ssh_conn_id, timeout=self.timeout)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/ssh/hooks/ssh.py", line 109, in __init__
    conn = self.get_connection(self.ssh_conn_id)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/hooks/base.py", line 63, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `crawler_server` isn't defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/ssh/operators/ssh.py", line 171, in execute
    raise AirflowException("SSH operator error: {}".format(str(e)))
airflow.exceptions.AirflowException: SSH operator error: The conn_id `crawler_server` isn't defined
[2020-12-28 13:36:23,032] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=foodpanda, task_id=t1, execution_date=20201227T010000, start_date=20201228T053622, end_date=20201228T053623
[2020-12-28 13:36:23,069] {local_task_job.py:118} INFO - Task exited with return code 1
