[2020-12-26 09:00:03,041] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [queued]>
[2020-12-26 09:00:03,044] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [queued]>
[2020-12-26 09:00:03,044] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-26 09:00:03,044] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-26 09:00:03,044] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-26 09:00:03,052] {taskinstance.py:1038} INFO - Executing <Task(SSHOperator): t1> on 2020-12-25T01:00:00+00:00
[2020-12-26 09:00:03,054] {standard_task_runner.py:51} INFO - Started process 9584 to run task
[2020-12-26 09:00:03,056] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 't1', '2020-12-25T01:00:00+00:00', '--job-id', '51', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpf10_ovcp']
[2020-12-26 09:00:03,056] {standard_task_runner.py:76} INFO - Job 51: Subtask t1
[2020-12-26 09:00:03,074] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [running]> on host dataiku
[2020-12-26 09:00:03,089] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2020-12-25T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-25T01:00:00+00:00
[2020-12-26 09:00:03,089] {ssh.py:90} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2020-12-26 09:00:03,092] {base.py:74} INFO - Using connection to: id: crawler_server. Host: 172.16.16.119, Port: 22, Schema: , Login: ub, Password: XXXXXXXX, extra: None
[2020-12-26 09:00:03,092] {ssh.py:197} WARNING - Remote Identification Change is not verified. This wont protect against Man-In-The-Middle attacks
[2020-12-26 09:00:03,093] {ssh.py:202} WARNING - No Host Key Verification. This wont protect against Man-In-The-Middle attacks
[2020-12-26 09:00:03,099] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2020-12-26 09:00:03,110] {transport.py:1819} INFO - Authentication (password) successful!
[2020-12-26 09:00:03,110] {ssh.py:109} INFO - Running command: echo "airflow"
[2020-12-26 09:00:03,280] {ssh.py:141} INFO - airflow
[2020-12-26 09:00:03,290] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=foodpanda, task_id=t1, execution_date=20201225T010000, start_date=20201226T010003, end_date=20201226T010003
[2020-12-26 09:00:03,306] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2020-12-26 09:00:03,348] {local_task_job.py:118} INFO - Task exited with return code 0
[2020-12-28 10:34:08,909] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [queued]>
[2020-12-28 10:34:08,912] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [queued]>
[2020-12-28 10:34:08,912] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 10:34:08,912] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-28 10:34:08,912] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 10:34:08,921] {taskinstance.py:1038} INFO - Executing <Task(SSHOperator): t1> on 2020-12-25T01:00:00+00:00
[2020-12-28 10:34:08,923] {standard_task_runner.py:51} INFO - Started process 22540 to run task
[2020-12-28 10:34:08,925] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 't1', '2020-12-25T01:00:00+00:00', '--job-id', '59', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpls2lulj1']
[2020-12-28 10:34:08,926] {standard_task_runner.py:76} INFO - Job 59: Subtask t1
[2020-12-28 10:34:08,942] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [running]> on host dataiku
[2020-12-28 10:34:08,957] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2020-12-25T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-25T01:00:00+00:00
[2020-12-28 10:34:08,957] {ssh.py:90} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2020-12-28 10:34:08,960] {base.py:74} INFO - Using connection to: id: crawler_server. Host: 172.16.16.119, Port: 22, Schema: , Login: ub, Password: XXXXXXXX, extra: None
[2020-12-28 10:34:08,960] {ssh.py:197} WARNING - Remote Identification Change is not verified. This wont protect against Man-In-The-Middle attacks
[2020-12-28 10:34:08,960] {ssh.py:202} WARNING - No Host Key Verification. This wont protect against Man-In-The-Middle attacks
[2020-12-28 10:34:08,964] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2020-12-28 10:34:08,974] {transport.py:1819} INFO - Authentication (password) successful!
[2020-12-28 10:34:08,974] {ssh.py:109} INFO - Running command: echo "airflow"
[2020-12-28 10:34:09,091] {ssh.py:141} INFO - airflow
[2020-12-28 10:34:09,102] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=foodpanda, task_id=t1, execution_date=20201225T010000, start_date=20201228T023408, end_date=20201228T023409
[2020-12-28 10:34:09,118] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2020-12-28 10:34:09,140] {local_task_job.py:118} INFO - Task exited with return code 0
[2020-12-28 13:36:22,656] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [queued]>
[2020-12-28 13:36:22,681] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [queued]>
[2020-12-28 13:36:22,681] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 13:36:22,681] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-28 13:36:22,681] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-28 13:36:22,694] {taskinstance.py:1038} INFO - Executing <Task(SSHOperator): t1> on 2020-12-25T01:00:00+00:00
[2020-12-28 13:36:22,696] {standard_task_runner.py:51} INFO - Started process 23146 to run task
[2020-12-28 13:36:22,698] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 't1', '2020-12-25T01:00:00+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpzdw4t2fq']
[2020-12-28 13:36:22,699] {standard_task_runner.py:76} INFO - Job 2: Subtask t1
[2020-12-28 13:36:22,782] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.t1 2020-12-25T01:00:00+00:00 [running]> on host dataiku
[2020-12-28 13:36:22,855] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2020-12-25T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-25T01:00:00+00:00
[2020-12-28 13:36:22,856] {ssh.py:90} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2020-12-28 13:36:22,884] {taskinstance.py:1396} ERROR - SSH operator error: The conn_id `crawler_server` isn't defined
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/ssh/operators/ssh.py", line 92, in execute
    self.ssh_hook = SSHHook(ssh_conn_id=self.ssh_conn_id, timeout=self.timeout)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/ssh/hooks/ssh.py", line 109, in __init__
    conn = self.get_connection(self.ssh_conn_id)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/hooks/base.py", line 63, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `crawler_server` isn't defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/providers/ssh/operators/ssh.py", line 171, in execute
    raise AirflowException("SSH operator error: {}".format(str(e)))
airflow.exceptions.AirflowException: SSH operator error: The conn_id `crawler_server` isn't defined
[2020-12-28 13:36:22,885] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=foodpanda, task_id=t1, execution_date=20201225T010000, start_date=20201228T053622, end_date=20201228T053622
[2020-12-28 13:36:22,950] {local_task_job.py:118} INFO - Task exited with return code 1
