[2020-12-25 15:58:37,156] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.also_run_this 2020-12-25T07:58:33.365874+00:00 [queued]>
[2020-12-25 15:58:37,159] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.also_run_this 2020-12-25T07:58:33.365874+00:00 [queued]>
[2020-12-25 15:58:37,159] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 15:58:37,159] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-25 15:58:37,159] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 15:58:37,169] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): also_run_this> on 2020-12-25T07:58:33.365874+00:00
[2020-12-25 15:58:37,170] {standard_task_runner.py:51} INFO - Started process 18013 to run task
[2020-12-25 15:58:37,172] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 'also_run_this', '2020-12-25T07:58:33.365874+00:00', '--job-id', '70', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpdn1e5d5m']
[2020-12-25 15:58:37,173] {standard_task_runner.py:76} INFO - Job 70: Subtask also_run_this
[2020-12-25 15:58:37,191] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.also_run_this 2020-12-25T07:58:33.365874+00:00 [running]> on host dataiku
[2020-12-25 15:58:37,207] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2020-12-25T07:58:33.365874+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2020-12-25T07:58:33.365874+00:00
[2020-12-25 15:58:37,208] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2020-12-25 15:58:37,208] {bash.py:158} INFO - Running command: sudo docker run -d hello-world
[2020-12-25 15:58:37,212] {bash.py:169} INFO - Output:
[2020-12-25 15:58:37,216] {bash.py:173} INFO - sudo: no tty present and no askpass program specified
[2020-12-25 15:58:37,217] {bash.py:177} INFO - Command exited with return code 1
[2020-12-25 15:58:37,220] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2020-12-25 15:58:37,220] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=foodpanda, task_id=also_run_this, execution_date=20201225T075833, start_date=20201225T075837, end_date=20201225T075837
[2020-12-25 15:58:37,264] {local_task_job.py:118} INFO - Task exited with return code 1
