[2020-12-25 16:22:50,897] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t2 2020-12-25T08:22:45.532304+00:00 [queued]>
[2020-12-25 16:22:50,900] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.t2 2020-12-25T08:22:45.532304+00:00 [queued]>
[2020-12-25 16:22:50,900] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 16:22:50,900] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-25 16:22:50,900] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 16:22:50,908] {taskinstance.py:1038} INFO - Executing <Task(SSHOperator): t2> on 2020-12-25T08:22:45.532304+00:00
[2020-12-25 16:22:50,911] {standard_task_runner.py:51} INFO - Started process 22687 to run task
[2020-12-25 16:22:50,913] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 't2', '2020-12-25T08:22:45.532304+00:00', '--job-id', '78', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpordko47f']
[2020-12-25 16:22:50,913] {standard_task_runner.py:76} INFO - Job 78: Subtask t2
[2020-12-25 16:22:50,931] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.t2 2020-12-25T08:22:45.532304+00:00 [running]> on host dataiku
[2020-12-25 16:22:50,945] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2020-12-25T08:22:45.532304+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2020-12-25T08:22:45.532304+00:00
[2020-12-25 16:22:50,945] {ssh.py:90} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2020-12-25 16:22:50,948] {base.py:74} INFO - Using connection to: id: crawler_server. Host: 172.16.16.119, Port: 22, Schema: , Login: ub, Password: XXXXXXXX, extra: None
[2020-12-25 16:22:50,948] {ssh.py:197} WARNING - Remote Identification Change is not verified. This wont protect against Man-In-The-Middle attacks
[2020-12-25 16:22:50,949] {ssh.py:202} WARNING - No Host Key Verification. This wont protect against Man-In-The-Middle attacks
[2020-12-25 16:22:50,952] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_7.6p1)
[2020-12-25 16:22:50,963] {transport.py:1819} INFO - Authentication (password) successful!
[2020-12-25 16:22:50,963] {ssh.py:109} INFO - Running command: docker  ps -a 2>&1 | tee -a  test.txt
[2020-12-25 16:22:51,142] {ssh.py:141} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2020-12-25 16:22:51,154] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=foodpanda, task_id=t2, execution_date=20201225T082245, start_date=20201225T082250, end_date=20201225T082251
[2020-12-25 16:22:51,174] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2020-12-25 16:22:51,207] {local_task_job.py:118} INFO - Task exited with return code 0
