[2020-12-25 17:12:09,675] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.docker_op_tester 2020-12-25T09:12:05.592380+00:00 [queued]>
[2020-12-25 17:12:09,678] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: foodpanda.docker_op_tester 2020-12-25T09:12:05.592380+00:00 [queued]>
[2020-12-25 17:12:09,678] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 17:12:09,678] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2020-12-25 17:12:09,678] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2020-12-25 17:12:09,686] {taskinstance.py:1038} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2020-12-25T09:12:05.592380+00:00
[2020-12-25 17:12:09,688] {standard_task_runner.py:51} INFO - Started process 31917 to run task
[2020-12-25 17:12:09,690] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'foodpanda', 'docker_op_tester', '2020-12-25T09:12:05.592380+00:00', '--job-id', '46', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ssh_practice.py', '--cfg-path', '/tmp/tmpztxlukn2']
[2020-12-25 17:12:09,690] {standard_task_runner.py:76} INFO - Job 46: Subtask docker_op_tester
[2020-12-25 17:12:09,706] {logging_mixin.py:103} INFO - Running <TaskInstance: foodpanda.docker_op_tester 2020-12-25T09:12:05.592380+00:00 [running]> on host dataiku
[2020-12-25 17:12:09,720] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=arthur.sl.lin
AIRFLOW_CTX_DAG_ID=foodpanda
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2020-12-25T09:12:05.592380+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2020-12-25T09:12:05.592380+00:00
[2020-12-25 17:12:09,724] {docker.py:287} INFO - Pulling docker image hello-world
[2020-12-25 17:12:13,423] {docker.py:301} INFO - latest: Pulling from library/hello-world
[2020-12-25 17:12:14,471] {docker.py:301} INFO - 0e03bdcc26d7: Pulling fs layer
[2020-12-25 17:12:15,435] {docker.py:301} INFO - 0e03bdcc26d7: Downloading
[2020-12-25 17:12:15,435] {docker.py:301} INFO - 0e03bdcc26d7: Verifying Checksum
[2020-12-25 17:12:15,436] {docker.py:301} INFO - 0e03bdcc26d7: Download complete
[2020-12-25 17:12:15,436] {docker.py:301} INFO - 0e03bdcc26d7: Extracting
[2020-12-25 17:12:15,479] {docker.py:301} INFO - 0e03bdcc26d7: Pull complete
[2020-12-25 17:12:15,485] {docker.py:296} INFO - Digest: sha256:1a523af650137b8accdaed439c17d684df61ee4d74feac151b5b337bd29e7eec
[2020-12-25 17:12:16,414] {docker.py:301} INFO - linux: Pulling from library/hello-world
[2020-12-25 17:12:17,266] {docker.py:296} INFO - Digest: sha256:16afe05194b3482b5429f8630be3a29ed18ca1f102d0b1c720573382b9c46bcf
[2020-12-25 17:12:18,137] {docker.py:301} INFO - nanoserver-1709: Pulling from library/hello-world
[2020-12-25 17:12:18,137] {docker.py:224} INFO - Starting docker container from image hello-world
[2020-12-25 17:12:18,397] {docker.py:263} INFO - Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
[2020-12-25 17:12:18,580] {xcom.py:238} ERROR - Could not serialize the XCom value into JSON. If you are using pickles instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2020-12-25 17:12:18,580] {taskinstance.py:1396} ERROR - Object of type 'bytes' is not JSON serializable
Traceback (most recent call last):
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1303, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1833, in xcom_push
    session=session,
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/xcom.py", line 88, in set
    value = XCom.serialize_value(value)
  File "/home/ub/airflow/env/lib/python3.6/site-packages/airflow/models/xcom.py", line 235, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
[2020-12-25 17:12:18,581] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=foodpanda, task_id=docker_op_tester, execution_date=20201225T091205, start_date=20201225T091209, end_date=20201225T091218
[2020-12-25 17:12:18,617] {local_task_job.py:118} INFO - Task exited with return code 1
